config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
  end
  get "about", to: "pages#about"
  resources :contacts, only: :create
  get 'contact-us', to: "contacts#new", as: "new_contact"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  # Contact form validations
  validates :name, presence: true
  validates :email, presence: true
  validates :comments, presence: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_attached_file :avatar,
                    :styles => { :medium => "300x300", :thumb => "100x100" },
                    :default_url => "/images/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  belongs_to :plan
  has_one :profile
  
  attr_accessor :stripe_card_token
  # If Pro user passes validations (email, password, etc..).
  # then call Stripe and tell Stripe to set up a subscription
  # upon chargin the customer's card
  # Stripe responds back with customer data.
  # Store customer.id as the customer token and save the user
  def save_with_subscription
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  # Whilelist the following form fields so that we can process them, if coming from
  # a Devise sign up form
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:stripe_card_token, :email, :password, :password_confirmation) }
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  # GET request to /contact-us
  # Show new contact form
  def new
    @contact = Contact.new
  end
  
  #POST request to /contacts
  def create
    # Mass assignment of form fields into Contact object
    @contact = Contact.new(contact_params)
    # Save the Contact object to the database
    if @contact.save
      # Store form fields via parameters into variables
      name = params[:contact][:name]
      email = params[:contact][:email]
      body = params[:contact][:comments]
      # Plug variables into the Contact Mailer email method
      ContactMailer.contact_email(name, email, body).deliver
      # Store success message in flash hash and redirect to the new action
      flash[:success] = "Message sent."
      redirect_to new_contact_path
    else
      # If Contact object doesn't save, store errors in flash hash,
      # and redirect to the new action
      flash[:danger] = @contact.errors.full_messages.join(", ")
      redirect_to new_contact_path
    end
  end
  
  private
  # To collect data from form, we need to use strong parameters
  # and whitelist the form fields
    def contact_params
      params.require(:contact).permit(:name, :email, :comments)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 
 def home
   # GET request for "/"" which is our home page
   @basic_plan = Plan.find(1)
   @pro_plan = Plan.find(2)
 end
 
 def about
 end
 
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :only_current_user
  
  # GET to /users/:user_id/profile/new
  def new
    # Render blank profile details form
    @profile = Profile.new
  end
  
  # POST to /users/:user_id/profile
  def create
    # Ensure that we have the user who is filling out form
    @user = User.find( params[:user_id] )
    @profile = @user.build_profile( profile_params )
    # Create profile linked to this specific user
    if @profile.save
      flash[:success] = "Profile updated!"
      redirect_to user_path(id: params[:user_id])
    else
      render action: :new
    end
  end
  
  # GET to /users/:user_id/profile/edit
  def edit
    @user = User.find( params[:user_id])
    @profile = @user.profile
  end
  
  # PUT to /users/:user_id/profile
  def update
    # Retrieve the user from the database
    @user = User.find( params[:user_id] )
    # Retrieve that user's profile
    @profile = @user.profile
    # Mass assign edited profile attributes and save (update)
    if @profile.update_attributes(profile_params)
      flash[:success] = "Profile updated!"
      # Redirect user to their profile page
      redirect_to user_path(id: params[:user_id])
    else
      render action :edit
    end
  end
  
  private
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :avatar, :job_title, :phone_number, :contact_email, :description)
    end
    
    def only_current_user
      @user = User.find( params[:user_id] )
      redirect_to(root_path) unless @user == current_user
    end
  
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :select_plan, only: :new
  # Extend default Devise gem behavior so that users signing up
  # with the Pro account (plan ID 2) save with a special Stripe
  # subscription function. Otherwise Devise signs up user as usual
  def create
    super do |resource|
      if params[:plan]
        resource.plan_id = params[:plan]
        if resource.plan_id == 2
          resource.save_with_subscription
        else
          resource.save
        end
      end
    end
  end
  
  private
    def select_plan
      unless (params[:plan] == '1' || params[:plan] == '2')
        flash[:notice] = "Please select a membership plan to sign up."
        redirect_to root_url
      end
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  # GET to /users
  def index
    @users = User.includes(:profile)
  end
  
  # GET to /users/:id
  def show
   @user = User.find( params[:id] )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def job_title_icon
    if @user.profile.job_title == "Developer"
      "<i class='fa fa-code'></i>".html_safe
    elsif @user.profile.job_title == "Entrepreneur"
      "<i class='fa fa-lightbulb-o'></i>".html_safe
    elsif @user.profile.job_title == "Investor"
      "<i class='fa fa-dollar'></i>".html_safe
    end
  end
end

app/views/contacts/new.html.erb
<div class="ui container">
  <div class="ui two column centered grid">
    <div class="column">
      <div class="ui form">
        <h2 class="ui dividing header">Contact Us</h2>
        <%= form_for @contact do |f| %>
          <div class="field">
            <%= f.label :name %>
            <%= f.text_field :name %>
          </div>
  
          <div class="field">
            <%= f.label :email %>
            <%= f.text_field :email %>
          </div>
  
          <div class="field">  
            <%= f.label :comments %>
            <%= f.text_area :comments %>
          </div>
  
          <%= f.submit "Submit", class: "ui button primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="top">
  <div class="ui container">
    <div class="ui secondary inverted stackable menu">
      <%= link_to root_path, class: "header item" do %>
        <i class="users icon"></i>
        DevMatch
      <% end %>
      <% if user_signed_in? %>
        <%= link_to "Community", users_path, class: "item" %>
      <% end %>
      <%= link_to "About", about_path, class: "item" %>
      <%= link_to "Contact Us", new_contact_path, class: "item" %>
      <div class="right menu">
        <% if user_signed_in? %>
          <div class="ui dropdown item">
            Hello <%= current_user.profile.first_name if current_user.profile %> <i class="icon dropdown"></i>
            <div class="menu">
              <%= link_to "Edit Account", edit_user_registration_path, class: "item" %>
              <%= link_to "Profile", user_path(id: current_user.id), class: "item" %>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "item" %>
            </div>
          </div>
          
        <% else %>
          <%= link_to "Sign In", new_user_session_path, class: "ui inverted button" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevMatch</title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://js.stripe.com/v2/', type: 'text/javascript' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="main-content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="ui container">
  <h1>About Us</h1>
  <p>
    We are DevMatch. Our company focuses on creating an exclusive community for
    developers, investors and entrepreneurs to meet.
  </p>
</div>

app/views/pages/home.html.erb
<div class="hero">
  <div class="ui text container center">
    <h1 class="header inverted">Welcome to DevMatch</h1>
    <h3>An online community where entrepreneurs, investors and developers can meet</h3>
  </div>
</div>
<div class="main">
  <div class="ui container">
    <% if user_signed_in? %>
      <div class="ui two column grid">
        <div class="ui column">
          <h2>Your Profile</h2>
          <% if current_user.profile %>
            <%= link_to "Edit your profile", edit_user_profile_path( user_id: current_user.id ), class: "ui button large" %>
            <%= link_to "View your profile", user_path( id: current_user.id ), class: "ui button large" %>
          <% else %>
            <p>Create your profile so you can share your information with the community</p>
            <%= link_to "Create your profile", new_user_profile_path( user_id: current_user.id ), class: "fluid ui button large" %>
          <% end %>
        </div>
        <div class="ui column">
          <h2>The Community</h2>
          <p>Visit the community to meet developers, entrepreneurs and investors</p>
          <%= link_to "Visit the community", users_path, class: "fluid ui button large" %>
        </div>
      </div>
    <% else %>
      <div class="ui two column grid">
        <div class="column">
          <div class="ui raised segment">
            <div class="ui ribbon primary label">Basic</div>
            <span>free</span>
            <p>Sign up for free and get basic access to the community.</p>
            <%= link_to "Sign up with Basic", new_user_registration_path(plan: @basic_plan.id), class: "fluid ui button primary large" %>
          </div>
        </div>
        <div class="column">
          <div class="ui raised segment">
            <div class="ui ribbon yellow label">Pro</div>
            <span>$10 per month</span>
            <p>Sign up for the Pro account for $10/month and get access to the community and contact information.</p>
            <%= link_to "Sign up with Pro", new_user_registration_path(plan: @pro_plan.id), class: "fluid ui button positive large" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, :html => { :multipart => true } do |f| %>
 <div class="field">
   <%= f.label :first_name %>
   <%= f.text_field :first_name %>
 </div>
 <div class="field">
   <%= f.label :last_name %>
   <%= f.text_field :last_name %>
 </div>
 <div class="field">
   <%= f.label :avatar %>
   <%= f.file_field :avatar %>
 </div>
 <div class="field">
   <%= f.label :job_title %>
   <%= f.select :job_title, ['Developer', 'Entrepreneur', 'Investor'], {}, class: "ui dropdown" %>
 </div>
 <div class="field">
   <%= f.label :phone_number %>
   <%= f.text_field :phone_number %>
 </div>
 <div class="field">
   <%= f.label :contact_email %>
   <%= f.text_field :contact_email %>
 </div>
 <div class="field">
   <%= f.label :description %>
   <%= f.text_area :description %>
 </div>
 <div class="field">
   <%= f.submit "Update Profile", class: "ui button positive" %>
 </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="ui container">
  <div class="ui two column centered grid">
    <div class="column">
      <div class="ui form">
        <h2 class="ui dividing header">Edit Your Profile</h2>
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="ui container">
  <div class="ui two column centered grid">
    <div class="column">
      <div class="ui form">
        <h2 class="ui dividing header">Create Your Profile</h2>
        <p>Be a part of the DevMatch community and fill out your profile</p>
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="ui container">
  <div class="ui header">
    <h1>DevMatch Community</h1>
    <p>Welcome to the DevMatch community. Users must fill out their profile in order to be visible in the community</p>
  </div>
  
  <div class="ui centered cards">
    <% @users.each do |user| %>
      <% if user.profile %>
        <div class="ui card">
          <div class="image">
            <%= image_tag user.profile.avatar.url %>
          </div>
          <div class="center aligned content">
            <span class="header"><%= user.profile.first_name %> <%= user.profile.last_name %></span>
            <%= user.profile.job_title %><br>
            <% if user.plan_id == 2 %>
              <div class="ui yellow label">PRO</div>
            <% else %>
              <div class="ui label">BASIC</div>
            <% end %>
          </div>
          <div class="center aligned content">
            <%= link_to "View Profile", user_path(id: user.id) %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="ui container">
  <div class="ui grid">
    <div class="three wide column">
      <div class="ui raised center aligned segments">
        <div class="ui segment">
          <%= image_tag @user.profile.avatar.url, class: "ui centered circular image" %>
        </div>
        <div class="ui segment">
          <h2><%= @user.profile.first_name %> <%= @user.profile.last_name %></h2>
          <%= @user.profile.job_title %>
        </div>
      </div>
    </div>
    <div class="eight wide column">
      <div class="ui raised green segment">
        <div class="ui header">
          Description
        </div>
        <p><%= @user.profile.description %></p>
      </div>
      <% if current_user.plan_id == 2 %>
        <div class="ui raised blue segment">
          <div class="ui header">
            Contact Information
          </div>
          <label>Phone: </label><%= @user.profile.phone_number %></br>
          <label>Email: </label><%= @user.profile.contact_email %>
        </div>
      <% end %>
    </div>
  </div>
</div>